apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spre-stonadsstatistikk
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  replicas:
    min: 1
    max: 6
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  webproxy: true
  secureLogs:
    enabled: true
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/service_user
        kvPath: /serviceuser/data/prod/srvsprestonad
  env:
  - name: KAFKA_BOOTSTRAP_SERVERS
    value: a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443,a01apvl00148.adeo.no:8443,a01apvl00149.adeo.no:8443,a01apvl00150.adeo.no:8443
  - name: KAFKA_RAPID_TOPIC
    value: helse-rapid-v1
  - name: KAFKA_CONSUMER_GROUP_ID
    value: spre-stonadsstatistikk-v2
  - name: KAFKA_RESET_POLICY
    value: none
  - name: DATABASE_HOST
    value: a01dbvl020.adeo.no
  - name: DATABASE_PORT
    value: "5432"
  - name: DATABASE_NAME
    value: spre-stonadsstatistikk
  - name: DATABASE_VAULT_MOUNT_PATH
    value: postgresql/prod-fss/
